#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause

NUM_TASKS=3
TASKS=(01-permutari 02-combinari 03-soricel)
NUM_TESTS=(8 11 10)

TIMEOUT_CPP=3
TIMEOUT_JAVA=6
TIMEOUT_RUST=3
TIMEOUT_PYTHON=6

DIRNAME=$(realpath $(dirname "${0}"))
source "${DIRNAME}"/../../utils/base_check.sh
