# SPDX-License-Identifier: BSD-3-Clause

PYTHON ?= python3
MINHEAP = minheap.py
MAXHEAP = maxheap.py

.PHONY: run run-min run-max clean

run: run-min run-max

run-min:
	$(PYTHON) $(MINHEAP)

run-max:
	$(PYTHON) $(MAXHEAP)

clean:
	@:
