#!/usr/bin/env python3
import sys


def main():
    [_, file_in, file_ref, file_out] = sys.argv

    edges_ref = []
    edges_out = []

    with open(file_out) as f:
        [edges] = [int(x) for x in next(f).split()]
        for _ in range(edges):
            edges_out.append(sorted([int(x) for x in next(f).split()]))
        edges_out = sorted(edges_out)

    with open(file_ref) as f:
        [edges] = [int(x) for x in next(f).split()]
        for _ in range(edges):
            edges_ref.append(sorted([int(x) for x in next(f).split()]))
        edges_ref = sorted(edges_ref)

    if len(edges_ref) != len(edges_out):
        sys.stdout.write('\nNumar incorect de muchii critice (%d vs %d).\t' % (
            len(edges_ref), len(edges_out)))
        sys.exit(1)

    if edges_ref != edges_out:
        sys.stdout.write('\nMuchii critice identificate gresit.\t')
        sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()
