#!/usr/bin/env python
import sys

def main():
	[_, file_in, file_ref, file_out] = sys.argv

	ref_no = None
	out_no = None
	eps = 1e-3

	with open(file_ref) as f:
		ref_no = float(next(f).strip())
	with open(file_out) as f:
		out_no = float(next(f).strip())
	if abs(ref_no - out_no) > eps:
		sys.stdout.write('\nSolutia gasita nu respecta |referinta - iesire| < 1e-3\t')
		sys.exit(1)

	sys.exit(0)
	

if __name__ == "__main__":
	main()
