#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause

NUM_TASKS=3
TASKS=(task-1 task-2 task-3)
NUM_TESTS=(10 10 10)

TIMEOUT_CPP=1
TIMEOUT_JAVA=10

DIRNAME=$(realpath $(dirname "${0}"))
source "${DIRNAME}"/../../utils/base_check.sh
