#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause

NUM_TASKS=2
TASKS=(01-mst-kruskal 02-mst-prim)
NUM_TESTS=(10 10)

TIMEOUT_CPP=1
TIMEOUT_JAVA=7
TIMEOUT_RUST=1
TIMEOUT_PYTHON=7

DIRNAME=$(realpath $(dirname "${0}"))
source "${DIRNAME}"/../../utils/base_check.sh
