#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause

NUM_TASKS=1
TASKS=(task-1)
NUM_TESTS=(10)

TIMEOUT_CPP=1
TIMEOUT_JAVA=2

DIRNAME=$(realpath $(dirname "${0}"))
source "${DIRNAME}"/../../utils/base_check.sh
