#!/usr/bin/env python
import sys


def main():
    [_, file_in, file_ref, file_out] = sys.argv

    ctc_ref = []
    ctc_out = []

    with open(file_out) as f:
        [ctcs] = [int(x) for x in next(f).split()]
        for _ in range(ctcs):
            ctc_out.append(sorted([int(x) for x in next(f).split()]))
        ctc_out = sorted(ctc_out)

    with open(file_ref) as f:
        [ctcs] = [int(x) for x in next(f).split()]
        for _ in range(ctcs):
            ctc_ref.append(sorted([int(x) for x in next(f).split()]))
        ctc_ref = sorted(ctc_ref)

    if len(ctc_ref) != len(ctc_out):
        sys.stdout.write('\nNumar incorect de componente tare conexe (%d vs %d).\t' % (
            len(ctc_ref), len(ctc_out)))
        sys.exit(1)

    if ctc_ref != ctc_out:
        sys.stdout.write(
            '\nComponente tare conexe neidentificare corect.\t' % (len(sol), n))
        sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()
