#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause

NUM_TASKS=4
TASKS=(01-scc 02-cv 03-ce 04-bcc)
NUM_TESTS=(10 10 10 10)

TIMEOUT_CPP=1
TIMEOUT_JAVA=4
TIMEOUT_RUST=1
TIMEOUT_PYTHON=4

# DN 2021: This is needed on some systems due to a high level of recursion on a big test (#8).
ulimit -s unlimited

DIRNAME=$(realpath $(dirname "${0}"))
source "${DIRNAME}"/../../utils/base_check.sh
