#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause

NUM_TASKS=3
TASKS=(01-ssm 02-scmax 03-rucsac)
NUM_TESTS=(10 10 10)

TIMEOUT_CPP=1
TIMEOUT_JAVA=1
TIMEOUT_RUST=1
TIMEOUT_PYTHON=1

DIRNAME=$(realpath $(dirname "${0}"))
source "${DIRNAME}"/../../utils/base_check.sh
