#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause

NUM_TASKS=4
TASKS=(task-1 task-2 task-3 task-4)
NUM_TESTS=(11 12 10 10)

TIMEOUT_CPP=3
TIMEOUT_JAVA=6

DIRNAME=$(realpath $(dirname "${0}"))
source "${DIRNAME}"/../../utils/base_check.sh
