#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause

NUM_TASKS=TODO
TASKS=(TODO)
NUM_TESTS=(TODO)

TIMEOUT_CPP=TODO
TIMEOUT_JAVA=TODO
TIMEOUT_RUST=TODO
TIMEOUT_PYTHON=TODO

DIRNAME=$(realpath $(dirname "${0}"))
source "${DIRNAME}"/../../utils/base_check.sh
