#!/usr/bin/env python
import sys


def check(n, sol):
    ok = True
    for i in range(1, n + 1):
        for j in range(1, i):
            if sol[i] == sol[j]:
                ok = False
            if abs(i - j) == abs(sol[i] - sol[j]):
                ok = False
    return ok


def main():
    [_, file_in, file_ref, file_out] = sys.argv

    with open(file_in) as f:
        [n] = [int(x) for x in next(f).split()]

    with open(file_out) as f:
        sol = [int(x) for x in next(f).split()]

    if len(sol) != n:
        sys.stdout.write('\nDimensiune vector sol gresita.\t')
        sys.exit(1)

    sol = [0] + sol

    if not check(n, sol):
        sys.stdout.write(
            '\nSolutia gasita nu reprezinta o asezare corecta a damelor.\t')
        sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()
