#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause

import sys


def main():
    [_, file_in, file_ref, file_out] = sys.argv

    nodes_ref = []
    nodes_out = []

    with open(file_out) as f:
        nodes_out = sorted([int(x) for x in f.readline().split()])

    with open(file_ref) as f:
        nodes_ref = sorted([int(x) for x in f.readline().split()])

    if len(nodes_ref) != len(nodes_out):
        sys.stdout.write('\nNumar incorect de noduri critice (%d vs %d).\t' % (
            len(nodes_ref), len(nodes_out)))
        sys.exit(1)

    if nodes_ref != nodes_out:
        sys.stdout.write('\nNoduri critice identificate gresit.\t')
        sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()
