#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause

import sys


def main():
    [_, file_in, file_ref, file_out] = sys.argv

    biconex_ref = []
    biconex_out = []

    with open(file_out) as f:
        [biconex] = [int(x) for x in next(f).split()]
        for _ in range(biconex):
            biconex_out.append(sorted([int(x) for x in next(f).split()]))
        biconex_out = sorted(biconex_out)

    with open(file_ref) as f:
        [biconex] = [int(x) for x in next(f).split()]
        for _ in range(biconex):
            biconex_ref.append(sorted([int(x) for x in next(f).split()]))
        biconex_ref = sorted(biconex_ref)

    if len(biconex_ref) != len(biconex_out):
        sys.stdout.write('\nNumar incorect de BCC-uri (%d vs %d).\t' % (
            len(biconex_ref), len(biconex_out)))
        sys.exit(1)

    if biconex_ref != biconex_out:
        sys.stdout.write('\nBCC-uri identificate gresit.\t')
        sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()
