#!/usr/bin/env python3
import os
import sys
sys.stdout = open(os.devnull, "w")


def get_value(file):
    with open(file) as f:
        val = float(f.readline().strip())
        return val


def main():
    value_out = get_value(sys.argv[2])
    value_ref = get_value(sys.argv[3])
    if abs(value_out - value_ref) <= 1e-3:
        sys.exit(0)
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
