#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause

NUM_TASKS=2
TASKS=(01-royfloyd 02-johnson)
NUM_TESTS=(10 10)

TIMEOUT_CPP=1
TIMEOUT_JAVA=8
TIMEOUT_RUST=1
TIMEOUT_PYTHON=8

DIRNAME=$(realpath $(dirname "${0}"))
source "${DIRNAME}"/../../utils/base_check.sh
