# SPDX-License-Identifier: BSD-3-Clause

name: CI test (solutions)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run solutions
        run: utils/run_solutions.sh

